ListaDB/ListaDB/Models/ConexaoBD.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;

namespace ListaDB.Models
{
    public class ConexaoBD
    {
        private static SqlConnection banco; 
        public static SqlConnection getConexao()
        {
            if (banco==null)
            {
                banco = new SqlConnection(@"Server=.\SENAI2022; Database=ListaDB; User id =sa; Password=senai.123;");
            }
            return banco; 
        }
    }
}

ListaDB/ListaDB/Models/ErrorViewModel.cs
using System;

namespace ListaDB.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ListaDB/ListaDB/Models/Sala.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ListaDB.Models
{
    public class Sala
    {
        public int SALAID { get; set; }
        public string SALADESC { get; set; }

    }
}

ListaDB/ListaDB/Controllers/HomeController.cs
using ListaDB.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ListaDB.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ListaDB/ListaDB/Controllers/SalaController.cs
using ListaDB.DAL;
using ListaDB.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ListaDB.Controllers
{
    public class SalaController : Controller
    {
        SalaDAO tbSala = new SalaDAO();

        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.listasalas = tbSala.getTodaAsSalas();
            return View();
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(string descricao)
        {
            Sala novaSala = new Sala();
            novaSala.SALADESC = descricao;
            tbSala.insertSala(novaSala);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Atualizar(int id)
        {
            ViewBag.salaAtualizar = tbSala.getTodaAsSalas().Where(x => x.SALAID == id).FirstOrDefault();
            return View();
        }
        [HttpPost]
        public IActionResult Atualizar(string codigo, string descricao)
        {

            Sala atualizaSala = new Sala();
            atualizaSala.SALAID = Convert.ToInt32(codigo);
            atualizaSala.SALADESC = descricao;
            tbSala.updateSala(atualizaSala);

            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Apagar(int id)
        {

            Sala atualizaSala = new Sala();
            atualizaSala.SALAID = Convert.ToInt32(id);
            tbSala.apgarSala(atualizaSala);

            return RedirectToAction("Index");
        }

    }

}

ListaDB/ListaDB/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ListaDB/ListaDB/Views/Sala/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<form method="post" action="Create">
<div class="form-group">
    <label for="descricao">Sala</label>
    <input type="text" class="form-control" id="descricao" name="descricao">

</div>


<a href="/Sala/Index" class="btn btn-secondary">Voltar</a>
<button type="submit" class="btn btn-primary">Submit</button>
</form>

ListaDB/ListaDB/Views/Sala/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h2>Gestão de Salas</h2>
<div>
    <a class="btn btn-sucess" href="Sala/Create"> Novo</a>
</div>
<div>
    <table>
        <tr>
            <td>#</td>
            <td>Descricao</td>
        </tr>
        @foreach (var item in ViewBag.listasalas)
        {
          <tr>
             <td>@item.SALAID</td>
             <td>@item.SALADESC</td>
             <td><a class="btn btn-primary" href="/Sala/Atualizar/@item.SALAID"> Editar </a></td>
          </tr>
        }

    </table>
</div>

ListaDB/ListaDB/Views/Sala/atualizar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>atualizar  Sala</h1>

<form method="post" action="atualizar">
    <div class="form-group">
        <label for="codigo">Código</label>
        <input type="text" class="form-control" id="codigo" value="@ViewBag.salaAtualizar.SALAID" name="codigo" readonly>
    </div>

    <div class="form-group">
        <label for="descricao">Sala</label>
        <input type="text" class="form-control" id="descricao" value="@ViewBag.salaAtualizar.SALADESC" name="descricao" readonly>
    </div>
    <a href="/Sala/Index" class="btn btn-secondary">Voltar</a>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

ListaDB/ListaDB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ListaDB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ListaDB</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sala" asp-action="Index">Sala</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ListaDB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>